services:
  postgres:
    image: postgres:18.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: webchatt
      POSTGRES_PASSWORD: lemotdepasse
      POSTGRES_DB: chat
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
